#!/usr/bin/env python3
"""Freeze vial-gui into a portable Windows build with modern PyInstaller.

Replaces the upstream `fbs freeze` pipeline (which is pinned to Python 3.6 +
PyInstaller 3.4 and does not run on the 3.12 dev venv). What fbs freeze would
provide is replicated here:

  - fbs_runtime expects resources FLAT NEXT TO THE EXE (fbs_runtime._frozen
    .get_resource_dirs() == dirname(sys.executable) on Windows), so
    qmk_settings.json and Icon.ico are copied next to Vial.exe after
    collecting.
  - fbs_runtime._frozen.BUILD_SETTINGS is normally injected by an fbs-generated
    PyInstaller runtime hook; we generate our own from
    src/build/settings/base.json.

Usage (from the repo root):
    venv/Scripts/python freeze_windows.py
Output:
    dist/Vial/Vial.exe   (portable folder - zip and run, no install needed)
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HOOK_DIR = ROOT / "build_frozen"
DIST = ROOT / "dist" / "Vial"


def main():
    settings = json.loads((ROOT / "src/build/settings/base.json").read_text(encoding="utf-8"))
    # mark the fork build so it is distinguishable from official releases
    settings["version"] += "-nuphy"

    HOOK_DIR.mkdir(exist_ok=True)
    hook = HOOK_DIR / "fbs_runtime_hook.py"
    hook.write_text(
        "# generated by freeze_windows.py - do not edit\n"
        "import fbs_runtime._frozen as _frozen\n"
        "_frozen.BUILD_SETTINGS = {}\n".format(json.dumps(settings, indent=4)),
        encoding="utf-8",
    )
    print("runtime hook:", hook)

    cmd = [
        ROOT / "venv/Scripts/pyinstaller.exe",
        "--noconfirm", "--clean",
        "--onedir", "--windowed",
        "--name", "Vial",
        "--icon", ROOT / "src/main/icons/Icon.ico",
        "--runtime-hook", hook,
        "--paths", ROOT / "src/main/python",
        "--distpath", ROOT / "dist",
        "--workpath", HOOK_DIR / "work",
        "--specpath", HOOK_DIR,
        ROOT / "src/main/python/main.py",
    ]
    print("running:", " ".join(str(c) for c in cmd))
    if subprocess.call([str(c) for c in cmd], cwd=str(ROOT)) != 0:
        return 1

    # fbs_runtime looks resources up next to the executable
    for rel in ("src/main/resources/base/qmk_settings.json", "src/main/icons/Icon.ico"):
        shutil.copy2(ROOT / rel, DIST / Path(rel).name)
        print("copied:", DIST / Path(rel).name)

    print("\nDONE:", DIST / "Vial.exe")
    return 0


if __name__ == "__main__":
    sys.exit(main())
